/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
import React, { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import AliceCarousel from 'react-alice-carousel';
import Link from 'next/link';
import heroStyles from '../styles/Hero.module.css';
import 'bootstrap/dist/css/bootstrap.css';
import BreakingNews from '../components/BreakingNews';
import Articles, { TopArticle } from '../components/Articles';
import Opportunities from '../components/Opportunities';
import Categories from '../components/Categories';
import client from '../graphql/uri';
import {
	GET_OPPORTUNITIES,
	GET_NEWS,
	GET_PUBS,
	GET_BREAKING_NEWS,
	GET_POSTS_HOME,
} from '../graphql/queries';
import AdSense from 'react-adsense';
import AliceCaroussel from '../components/AliceCaroussel';
import Videos from '../components/Videos';
export interface IState {
	breakingNews: {
		title: string;
		node: any;
	}[];
}

export interface IArticles {
	articles: {
		node: any;
	}[];
}

export interface IOpportunities {
	opportunities: {
		node: any;
	}[];
}

export default function Home({
	opportunities,
	news,
	pubs,
	breakingNews,
	artcleByCategorySante,
	artcleByCategoryBiodiversite,
	artcleByCategoryEnvironnement,
}) {
	const [breakingNews_, setBreakingNews] =
		useState<IState['breakingNews']>(breakingNews);

	const [articles, setArticles] = useState<IArticles['articles']>(news);
	const filteredArticles = articles.slice(6, 10);
	const topArcticles = articles.slice(10, 15);
	const slider = articles.slice(0, 5);

	let randomId = Math.floor(Math.random() * 20);
	const Toparticle = articles.filter((value, key, array) => key == 19);

	const [opportunities_, setOpportunities] =
		useState<IOpportunities['opportunities']>(opportunities);

	const handleDragStart = (e) => e.preventDefault();

	const items = [
		<Image
			key={1}
			src='/assets/image.webp'
			width={1600}
			height={300}
			onDragStart={handleDragStart}
			alt='ad'
		/>,
		<Image
			key={2}
			src='/assets/image2.webp'
			width={1600}
			height={300}
			onDragStart={handleDragStart}
			alt='ad'
		/>,
		<Image
			key={3}
			src='/assets/image3.webp'
			width={1600}
			height={300}
			onDragStart={handleDragStart}
			alt='ad'
		/>,
	];

	return (
		<div>
			<Head>
				<title>Environews RDC</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<script
					data-ad-client='ca-pub-2034102263729175'
					async
					src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'></script>
			</Head>

			<div className='container'>
				<div className={`row ${heroStyles.hero}`}>
					<AliceCaroussel />

					<div className='col-md-8 col-sm-12'>
						<div className={heroStyles.topNews}>
							<br />
							<br />
							<AliceCarousel
								mouseTracking
								items={topArcticles.map((article, index) => {
									return (
										<>
											<Link
												href='/[annee]/[mois]/[jour]/[slug]'
												as={`${article.node.uri}`}>
												<a>
													<div key={index} className={`${heroStyles.slider}`}>
														<img
															src={`${article.node.featuredImage.node.sourceUrl}`}
															alt={article.node.title}
															className={`w-100 ${heroStyles.imageSlider}`}
															style={{ objectFit: 'cover' }}
														/>
														<div className={`${heroStyles.textContainer}`}>
															<h5
																className={`border-start px-3 border-success border-5 ${heroStyles.slideTitle}`}>
																{article.node.title.split(':').length == 2
																	? article.node.title.split(':')[0]
																	: 'Environews'}
															</h5>
															<h4 className={`text-white`}>
																{article.node.title.split(':').length == 2
																	? article.node.title.split(':')[1]
																	: article.node.title.split(':')[0] + '.'}
															</h4>
														</div>
													</div>
												</a>
											</Link>
										</>
									);
								})}
								infinite
								disableDotsControls
								disableButtonsControls
								autoPlay
								animationDuration={400}
								autoPlayInterval={10000}
								animationType='fadeout'
								// autoWidth={true}
							/>
							{/* <span>
								{}
							</span> */}
						</div>
						<br />
						<br />
						<Articles articles={filteredArticles} />
					</div>
					<div className='mt-5 col-md-4 col-sm-12'>
						<BreakingNews breakingNews={breakingNews_} />
						<div className={heroStyles.pub}>
							<iframe
								title='OTFF 2021'
								width='100%'
								height='250'
								src='https://www.youtube.com/embed/wuhqkNhZQ78?autoplay=0&amp;rel=0&amp;mute=0'
								frameBorder='0'></iframe>
						</div>
						<Opportunities opportunities={opportunities_} />
					</div>
				</div>

				<Categories
					articles={artcleByCategoryEnvironnement}
					title='environement'
				/>
				<Categories
					articles={artcleByCategoryBiodiversite}
					title='biodiversite'
				/>
				<Categories articles={artcleByCategorySante} title='sante' />
			</div>
			<Videos title='Environews TV' />
			<div className='container'>
				<div className='row py-5'>
					<div className={`col-md-6 col-sm-12 px-3 ${heroStyles.editorChoice}`}>
						<h5 className='border-start px-2 mb-4 border-success border-5'>
							CHOIX DE L’EDITEUR
						</h5>
						<div className={heroStyles.editorChoiceContainer}>
							<Articles articles={filteredArticles} />
						</div>
					</div>
					<div
						className={`col-md-5 col-sm-12 px-3 ${heroStyles.similarContainer}`}>
						<h5 className='border-start px-2 border-success border-5'>
							TOP ARTICLES
						</h5>
						<div>
							{topArcticles.map((article, index) => (
								<TopArticle
									key={article.node.id}
									article={article}
									index={index}
								/>
							))}
						</div>
					</div>
				</div>
			</div>

			<div className={`mt-4 ${heroStyles.newsLetter}`}>
				<h3>NEWSLETTER</h3>
				<form>
					<input
						className='form-control form-control-lg'
						type='email'
						placeholder='Adresse Email'></input>
					<p>
						Inscrivez-vous à notre newsletter pour vous tenir au courant de nos
						activités.
					</p>
					<button>S'INSCRIRE</button>
				</form>
			</div>
		</div>
	);
}

export async function getStaticProps() {
	const opportunities = await client.query({ query: GET_OPPORTUNITIES });
	const news = await client.query({ query: GET_NEWS });
	const pubs = await client.query({ query: GET_PUBS });
	const breakingNews = await client.query({ query: GET_BREAKING_NEWS });
	const artcleByCategorySante = await client.query({
		query: GET_POSTS_HOME('sante'),
	});
	const artcleByCategoryEnvironnement = await client.query({
		query: GET_POSTS_HOME('environnement'),
	});
	const artcleByCategoryBiodiversite = await client.query({
		query: GET_POSTS_HOME('biodiversite'),
	});

	return {
		props: {
			news: news.data.posts.edges,
			pubs: pubs.data.publicites.edges,
			opportunities: opportunities.data.posts.edges,
			breakingNews: breakingNews.data.breakingNews.edges,
			artcleByCategoryBiodiversite:
				artcleByCategoryBiodiversite.data.posts.edges,
			artcleByCategoryEnvironnement:
				artcleByCategoryEnvironnement.data.posts.edges,
			artcleByCategorySante: artcleByCategorySante.data.posts.edges,
		},
	};
}
